substitutions:
  device_name: heatpump-listener
  friendly_name: Heat Pump Listener - Quatt
  time_timezone: "Europe/Amsterdam"
  throttling_value: 10s

packages:
  base: !include packages/base.yaml
  pcb: !include packages/pcb3.yaml
  heatpump1: !include
    file: packages/quatt.yaml
    vars:
      id_prefix: ""
      prefix: ""
      device_address: 0x01

switch:
  - platform: gpio
    pin: GPIO22
    name: Relay 1
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO23
    name: Relay 2
    restore_mode: RESTORE_DEFAULT_OFF


