esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2025.12.0
  project:
    name: "electropaultje.heatpump-listener"
    version: "0.9.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://electropaultje/modbus-spy-esphome@readout-function-6
  #- source: github://electropaultje/modbus-spy-esphome@latest-stable

logger:
  level: INFO

api:

ota:
  platform: esphome

wifi:
  power_save_mode: none
  ap:
    ssid: "heatpump"
    password: "heatpump"

captive_portal:

modbus_spy:
  id: modbusspy
  log_not_configured_data: false

light:
  - platform: binary
    id: led_yellow
    output: led_yellow_output

number:
  - platform: template
    name: "Flow sensor calibration"
    id: flow_sensor_calibration
    min_value: 1
    max_value: 1000
    mode: box
    step: 1
    restore_value: true
    optimistic: true
    entity_category: config
    unit_of_measurement: "pulses/l"

button:
  - platform: restart
    name: Restart heatpump listener
  - platform: factory_reset
    id: button_factory_reset

web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: sorting_group_alarms
      name: Alarms

script:
  - id: blink_light
    parameters:
      calling_component: string
    then:
      - if:
          condition:
            lambda: return true; //return id(green_led_select).state == calling_component;
          then:
            - light.turn_on: led_yellow
            - delay: 250ms
            - light.turn_off: led_yellow